[phases.setup]
nixPkgs = ["nodejs", "npm", "ffmpeg", "yt-dlp", "fontconfig", "freefont_ttf", "dejavu_fonts"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
